name: Auto Merge

on:
  check_run:
    types: [completed]

jobs:
  auto_merge:
    name: Auto Merge
    runs-on: ubuntu-latest
    steps:
      - name: echo event
        run: |
          echo "${{ toJson(github.event) }}"
