name: Update Dependencies

on:
  repository_dispatch:
    types: UpdateDependencies

jobs:
  test_latest:
    name: Test Latest
    runs-on: ubuntu-latest
    steps:
      - name: echo event
        run: |
          echo "${{ toJson(github.event.client_payload) }}"
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branchName }}
      - name: update versions
        if: github.event.client_payload.hasDependencyUpdates == true
        run: |
          echo "${{ github.event.client_payload.newGradleProperties }}" > gradle.properties
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          author: ${{ secrets.USERNAME }} <github@claymccoy.com>
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "update dependencies to platform version ${{ github.event.client_payload.platformVersion }}"
          branch: ${{ github.event.client_payload.platformVersion }}
          branch-suffix: timestamp
          title: "Update dependencies to platform version ${{ github.event.client_payload.platformVersion }}"
          body: |
            Event
            ```
            ${{ toJson(github.event.client_payload) }}
            ```
          labels: |
            updateDeps
